themes:
  - name: "kanagawa-paper-dark"
    colors:
      - "#1F1F28"
      - "#2A2A37"
      - "#363646"
      - "#393836"
      - "#435965"
      - "#698a9b"
      - "#8ea49e"
      - "#938AA9"
      - "#96ada7"
      - "#a292a3"
      - "#aca9a4"
      - "#b4a7b5"
      - "#c4746e"
      - "#c4b28a"
      - "#C8C093"
      - "#cc928e"
      - "#d4c196"
      - "#d5cd9d"
      - "#DCD7BA"
      - "#699469"
      - "#72a072"
      - "#000000"
  - name: "kanagawa-paper-light"
    colors:
      - "#f2f1ec"
      - "#e4e1d8"
      - "#c9cdd7"
      - "#c8c5bd"
      - "#adada5"
      - "#a989a3"
      - "#a7956a"
      - "#91b0bd"
      - "#8a9ab8"
      - "#8e8a80"
      - "#8b6e86"
      - "#858178"
      - "#84a098"
      - "#809ba7"
      - "#7e8faf"
      - "#7b958e"
      - "#737066"
      - "#6f8795"
      - "#6b7f9f"
      - "#666b70"
      - "#c27672"
      - "#c68582"
      - "#9e7e98"
      - "#9e9e96"
      - "#5d6267"
      - "#4f5357"
      - "#b29f71"
      - "#ffffff"
